Adiciona contéudo a seção Passo a Passo
pugpe/meetup-cookbook pull request #23
Opened 2019-10-20 21:55 UTC by naanadr

### Descrição da mudança

Foi adicionado ao arquivo `PASSO-A-PASSO.md` conteúdo considerado relevante para essa seção, com os principais cabeçalhos:

- Antes de organizar o evento
- Pondo as ideias no lugar
- Definir local e dia
- Outros pontos importantes

2019-10-21 01:59 UTC, davidpierre21 commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +- [ ] **Ter amiguinhos com vontade de ajudar você nessa jornada (não precisamos fazer tudo sozinhos, ne mesmo?)**
```suggestion
- [ ] **Ter amiguinhos com vontade de ajudar você nessa jornada (não precisamos fazer tudo sozinhos, não é mesmo?)**
```

2019-10-21 02:00 UTC, davidpierre21 commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  Se você é estudante em alguma Universidade/Faculdade/Escola e está querendo organizar o encontro onde você estuda, recomendamos que você converse com seus amiguinhos. Provavelmente, terá alguém que
```suggestion
  Se você é estudante em alguma Universidade/Faculdade/Escola e está querendo organizar o encontro onde você estuda, recomendamos que você converse com seus colegas. Provavelmente, terá alguém disposto a te ajudar em alguma coisa :smile: 
```

2019-10-21 02:02 UTC, davidpierre21 commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  Se infelizmente isso não ocorrer, relaxa temos pessoas muito legais e dispostas na organização do PUG-PE que podem te ajudar nessa empreitada nova.
```suggestion
  Se, infelizmente, isso não ocorrer, relaxa. Temos pessoas muito legais e dispostas na organização do PUG-PE que podem te ajudar nessa nova empreitada. 
```

2019-10-21 02:04 UTC, davidpierre21 commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  As vezes queremos atingir um público, mas não conseguimos chegar neles. Você conseguirá passar essa barreira? Você tem contatinhos para te ajudar nessa divulgação?
Não entendi bem essa, parte, tu poderia me explicar? Ou talvez deixar mais claro, não sei 🤷‍♂

2019-10-21 02:04 UTC, davidpierre21 commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  Pense em locais onde o evento ainda não ocorreu ou já tenha ocorrido a muito tempo. Para que assim mais pessoas possam agregar ao PUG e participar dos encontros.
```suggestion
  Pense em locais onde o evento ainda não ocorreu ou já tenha ocorrido há muito tempo. Para que assim mais pessoas possam agregar ao PUG e participar dos encontros.
```

2019-10-21 02:08 UTC, davidpierre21 commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  Alguns locais pedem que seja realizado o controle de entrada e saída, caso esse local que você escolheu seja esse tipo de local, realize o evento mesmo assim, mas lembre-se de utilizar algum sistem
Achei essa parte um pouco estranha, acho que no começo repete muito "local".
Também acho que seria mais interessante em vez de "realize o evento mesmo assim" trocar para algo do tipo "mas isso não é um impedimento para a realização do evento.
Talvez seja interessante sinalizar de forma mais clara que o Sympla é um exemplo de sistema de inscrição 🤷‍♂ 
O que tu achas?

2019-10-21 02:11 UTC, davidpierre21 commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  No caso, a disponibilidade desse local está compatível com o período do mês e até mesmo o mês que o evento deverá ocorrer? Verifique isso antes, **não deixe para verificar a disponibilidade encima
```suggestion
  No caso, a disponibilidade desse local está compatível com o período do mês e até mesmo o mês que o evento deverá ocorrer? Verifique isso antes, **não deixe para verificar a disponibilidade em cima da hora**, principalmente porque tentamos organizar encontros mensais.
```

2019-10-21 02:12 UTC, davidpierre21 commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  Temos muitas pessoas no grupo do PUG-PE, os membros mais ativos podem ajudar você a escolher o mehor dia e horário para ocorrer o evento. Recomendamos à você abrir uma enquete no Telegram com as op
```suggestion
  Temos muitas pessoas no grupo do PUG-PE, os membros mais ativos podem ajudar você a escolher o melhor dia e horário para a realização do evento. Recomendamos fazer uma enquete com as opções de dia/horário, o evento é para a comunidade, sendo assim, vamos fazer a comunidade participar das decisões também :smile: 
```

2019-10-21 02:13 UTC, davidpierre21 commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +    - [ ] Dia para abrir as inscrições
```suggestion
    - [ ] Dia para abrir as inscrições (Caso necessário)
```

2019-10-21 02:15 UTC, davidpierre21 commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  Agora que você tem a data do evento bem definida (espero que sejá com uma margem de 30 dias, porque você vai precisar), é hora de definir algumas datas importantes:
```suggestion
  Agora que você tem a data do evento bem definida(sugerimos que defina a data com antecedência, porque você vai precisar), é hora de definir algumas datas importantes:
```

2019-10-21 02:16 UTC, davidpierre21 commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +- Não deixe para organizar o evento encima da hora, tenha pelo menos um período de 1 mês para fazer tudo.
```suggestion
- Não deixe para organizar o evento em cima da hora, recomendamos que tenha pelo menos o período de 1 mês para fazer tudo.
```

2019-10-21 02:19 UTC, davidpierre21 commented
Fiz alguns comentários e sugestões, me diz o que tu achas das sugestões e dos comentários, se tu concordas, etc 😛

2019-10-21 20:55 UTC, davidpalves requested changes

2019-10-21 20:55 UTC, davidpierre21 commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  Caso esse local tenha muitas disponibilidade de horário, siga para o tópico abaixo.
```suggestion
  Caso esse local tenha muitos horários disponíveis, siga para o tópico abaixo.
```

2019-10-21 20:55 UTC, davidpierre21 commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  Caso esse local tenha muitas disponibilidade de horário, siga para o tópico abaixo.
```suggestion
  Caso esse local tenha muitos horários disponíveis, siga para o tópico abaixo.
```

2019-10-23 18:41 UTC, naanadr commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  As vezes queremos atingir um público, mas não conseguimos chegar neles. Você conseguirá passar essa barreira? Você tem contatinhos para te ajudar nessa divulgação?
Estava querendo falar que a gente (quem organiza) precisa saber previamente onde irá divulgar o evento. Exemplo:

```
Quero organizar o pug no porto digital, pra avisar pra galera das empresas que o pug existe. Mas eu vou ter como fazer divulgação junto a eles? Vou ter como trazer essa galera pros eventos? Os meios que vou fazer divulgação é acessivel pra eles?
```

Deu pra entender agora? .-.

2019-10-23 18:53 UTC, naanadr commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  Alguns locais pedem que seja realizado o controle de entrada e saída, caso esse local que você escolheu seja esse tipo de local, realize o evento mesmo assim, mas lembre-se de utilizar algum sistem
Dei uma mudada nessa parte, adicionei uns pontos a mais que aprendi esse mês kkkk

2019-10-25 19:17 UTC, davidpalves requested changes

2019-10-25 19:17 UTC, davidpalves commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +- [ ] **Ter amiguinhos com vontade de ajudar você nessa jornada (não precisamos fazer tudo sozinhos, não é mesmo?)**
Que que tu acha de trocar amiguinhos por colegas? Não que seja um grande problema deixar "amiguinhos" 
```suggestion
- [ ] **Ter colegas com vontade de ajudar você nessa jornada (não precisamos fazer tudo sozinhos, não é mesmo?)**
```

2019-10-25 19:17 UTC, davidpalves commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  Se, infelizmente, isso não ocorrer relaxa. Temos pessoas muito legais e dispostas na organização do PUG-PE que podem te ajudar nessa nova empreitada.
```suggestion
  Se, infelizmente, isso não ocorrer, relaxa. Temos pessoas muito legais e dispostas na organização do PUG-PE que podem te ajudar nessa nova empreitada. 
```

2019-10-25 19:17 UTC, davidpalves commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  Fazer divulgação, gerenciar submissão de palestras, montar grade de horario, organizar o evento no dia, resolver certificados, isso demanda tempo e não deve ser subestimado.
Não necessariamente num evento do PUG tem que ter certificado, né? Tu não acha que seria melhor sinalizar bem isso, pra que quem quiser organizar não ache que necessariamente tenha que fazer isso?

2019-10-25 19:17 UTC, davidpalves commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  Esse ponto está fortemente relacionado com o anterior, se você acha que sua disponibilidade não é suficiente para fazer tudo isso, recomendamos que você tenha mais alguém com você (mais de duas pes
Dizer que algo é desnecessário é meio forte, principalmente sem saber quem são as pessoas que tão organizando e como elas se organizam, ai sugeri isso aqui, mas se tu achar melhor escrever de outra forma :man_shrugging:
```suggestion
  Esse ponto está fortemente relacionado com o anterior, se você acha que sua disponibilidade não é suficiente para fazer tudo isso, recomendamos que você tenha mais alguém com você (mais de duas pessoas pode ser desnecessário). 
```

2019-10-25 19:17 UTC, davidpalves commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +- [ ] **Quero fazer um evento mais introdutorio ou avançado?**
Não sei se concordo muito com essa, acho que é possível e acho que desejável fazer um evento diverso que possa ser atrativo tanto pro público mais experiente, tanto pro público iniciante. Que que tu acha?

2019-10-25 19:17 UTC, davidpalves commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  As vezes queremos atingir um público, mas não conseguimos chegar neles. Você conseguirá passar essa barreira? Você tem contatinhos para te ajudar nessa divulgação?
Entendi! Mas não sei se tá claro do jeito que tá escrito, tu acha que vale a pena reescrever esse parágrafo?

2019-10-25 19:17 UTC, davidpierre21 commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  Ou conseguirá comportar o público que você está esperando? Pense bem nisso, a galera não tem frescura senta ate no chão, mas vamos pensar na segurança de todos :smile:
Eu sugeri trocar frescura por besteira porque acho mais ameno e neutro :stuck_out_tongue: 

```suggestion
  Ou conseguirá comportar o público que você está esperando? Pense bem nisso, a galera não tem besteira senta ate no chão, mas vamos pensar na segurança e conforto de todos :smile:
```

2019-10-25 19:17 UTC, davidpierre21 commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  Sabendo da elevada taxa de ausência no evento quando é preciso realizar inscrições e quando elas são gratuítas. Segue umas dicas de como sobreviver a isso:
```suggestion
  Sabendo da elevada taxa de ausência no evento quando é preciso realizar inscrições e quando elas são gratuítas. Segue umas dicas de como contornar isso: 
```

2019-10-25 19:17 UTC, davidpierre21 commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  No caso, a disponibilidade desse local está compatível com o período do mês e até mesmo o mês que o evento deverá ocorrer? Verifique isso antes, **não deixe para verificar a disponibilidade em cima
Achei essa tua alteração bem melhor, vou sugerir só uma pequena mudança, vê o que tu acha:

```suggestion
  No caso, a disponibilidade desse local está compatível com o período do mês e até mesmo o mês que o evento deverá ocorrer? Verifique isso antes. **Não deixe para verificar a disponibilidade em cima da hora**, principalmente porque tentamos organizar encontros mensais.
```

2019-10-25 20:28 UTC, naanadr commented on languages/portuguese/arquivos/PASSO-A-PASSO.md
> +  Ou conseguirá comportar o público que você está esperando? Pense bem nisso, a galera não tem frescura senta ate no chão, mas vamos pensar na segurança de todos :smile:
O `besteira` saiu como um modo de falar, mas realmente pode ser entendido errado por outras pessoas.

2019-10-25 21:03 UTC, davidpalves approved these changes

2019-10-25 21:03 UTC, merged