Atualiza o CONTRIBUTING.pt do projeto
pugpe/meetup-cookbook pull request #24
Opened 2019-10-20 22:14 UTC by naanadr

### Descrição da mudança
Reformula algumas frases e adiciona referências (como o link das issues do projeto e do que é um pull request) a termos que possam ser desconhecidos para algumas pessoas.

2019-10-21 20:01 UTC, marcusgabrields requested changes

2019-10-21 20:01 UTC, marcusgabrields commented on languages/portuguese/CONTRIBUTING.md
> +Antes de sugerir, por favor veja se a mesma ideia já não foi [sugerida antes](https://github.com/pugpe/meetup-cookbook/issues) (algumas vezes você verá que não precisa criar uma nova sugestão).
```suggestion
Antes de sugerir, por favor veja se a mesma ideia já não foi [sugerida antes](https://github.com/pugpe/meetup-cookbook/issues). Caso a sua ideia tenha sido sugerida, não se esqueça de interagir na issue e ajudar a evoluir a ideia.
```

2019-10-21 20:10 UTC, naanadr commented on languages/portuguese/CONTRIBUTING.md
> +Antes de sugerir, por favor veja se a mesma ideia já não foi [sugerida antes](https://github.com/pugpe/meetup-cookbook/issues) (algumas vezes você verá que não precisa criar uma nova sugestão).
Fica massa assim, alterado o/

2019-10-22 22:14 UTC, marcusgabrields approved these changes

2019-10-22 22:14 UTC, merged