Adiciona algumas instruções para o dia do Evento no arquivo ORGANIZACAO-DIA.md
pugpe/meetup-cookbook pull request #3
Opened 2019-10-11 15:56 UTC by davidpierre21

Foram adicionadas dicas para que os organizadores/voluntários:
 - cheguem cedo ao local do evento, a fim de organizarem o lugar e resolverem qualquer imprevisto que possa surgir.
 - Apresentem, brevemente, o PUG-PE ao início de cada evento, a fim de que todos os novos participantes saibam o que é o PUG, uma comunidade e quais seus objetivos.

2019-10-12 03:11 UTC, naanadr requested changes

2019-10-12 03:11 UTC, naanadr commented on arquivos/ORGANIZACAO-DIA.md
> +### Chegue cedo
Se vamos usar Markdown seria legal seguir os padrões, um desses padrões é que se vc tem um H1, o header precisa ser o 2 e não o 3.

2019-10-12 03:11 UTC, naanadr commented on arquivos/ORGANIZACAO-DIA.md
> +### Chegue cedo
Como aqui vai ter mais conteúdo, como a definição de dia e tudo mais, seria legal inserir um `header 2` antes desses dois tópicos, algo como `Momentos antes do Grande Dia` ou algo assim..

2019-10-12 03:11 UTC, naanadr commented on arquivos/ORGANIZACAO-DIA.md
> +O PUG-PE é um evento que sempre recebe novos participantes e muitos, apesar de estarem participando do encontro, não conhecem a comunidade Python local ou, até mesmo, o que é uma comunidade. Por isso
Por que também não inserir um textinho para auxiliar as pessoas?

2019-10-12 03:11 UTC, naanadr commented on arquivos/ORGANIZACAO-DIA.md
> +
Inserir que é preciso além de organizar as cadeiras e o lugar, enfatizar que é preciso `SINALIZAR` (com banners ou até mesmo com papel) onde será o lugar kkkk  a gente falhou um pouco nisso nos últimos encontros.

2019-10-12 12:33 UTC, davidpierre21 commented on arquivos/ORGANIZACAO-DIA.md
> +O PUG-PE é um evento que sempre recebe novos participantes e muitos, apesar de estarem participando do encontro, não conhecem a comunidade Python local ou, até mesmo, o que é uma comunidade. Por isso
Textinho de apresentação? Pode ser, a ideia que tive nesse PR foi de adicionar algumas coisas mais básicas, pra que depois a gente fosse complementando a informação

2019-10-12 12:55 UTC, davidpierre21 commented on arquivos/ORGANIZACAO-DIA.md
> +### Chegue cedo
Fiz algumas alterações, dá uma olhada depois @naanadr

2019-10-12 15:39 UTC, naanadr requested changes

2019-10-12 15:39 UTC, naanadr commented on arquivos/ORGANIZACAO-DIA.md
> +>Aqui estão algumas instruções e dicas a serem seguidas para os organizadores ou voluntários do PUG-PE no dia do evento.
```suggestion
>Aqui estão algumas instruções e dicas a ser seguidas pelos organizadores ou voluntários do PUG-PE no dia do evento.
```

2019-10-12 15:39 UTC, naanadr commented on arquivos/ORGANIZACAO-DIA.md
> +preparando o projetor, entre outras coisas. Para isso, é interessante que as pessoas responsáveis cheguem mais cedo até mesmo para resolver qualquer imprevisto ainda antes do evento. Também é importa
```suggestion
Os responsáveis pela organização do meetup precisaram preparar o lugar do evento, por isso chegue cedo! Assim você poderá resolver imprevistos com mais calma, e organizar cadeiras, preparar datashow, receber os palestrantes e participantes.

Também é importante que haja uma sinalização de onde ocorrerá o evento, visto que muitas vezes os encontros acontecem, por exemplo, em salas de universidades, e como nem todos conhecem o local acabam se perdendo e não encontram com facilidade o local do evento.
```

2019-10-12 15:39 UTC, naanadr commented on arquivos/ORGANIZACAO-DIA.md
> +O PUG-PE é um evento que sempre recebe novos participantes e muitos, apesar de estarem participando do encontro, não conhecem a comunidade Python local ou, até mesmo, o que é uma comunidade. Por isso
ahhh beleza, então em outro arquivo a gente coloca. Talvez até no readme mesmo

2019-10-13 17:50 UTC, naanadr requested changes

2019-10-13 17:50 UTC, naanadr commented on arquivos/ORGANIZACAO-DIA.md
> +Os responsáveis pela organização do encontro precisarão preparar o local do evento, por isso chegue cedo! Assim você poderá resolver imprevistos com mais calma e organizar cadeiras, preparar o projet
Desculpa sugerir mudanças de novo nesse paragrafo, mas é que o texto está muito repetitivo. Vê se assim fica melhor:

```suggestion
As pessoas responsáveis pela organização muito provavelmente vão precisar preparar o lugar para o evento, organizando cadeiras, recebendo os palestrantes ou participantes. Resumindo, chegue cedo! Assim você poderá resolver imprevistos com mais calma (não esqueça de testar o projetor).
```

2019-10-13 17:50 UTC, naanadr commented on arquivos/ORGANIZACAO-DIA.md
> +Os responsáveis pela organização do encontro precisarão preparar o local do evento, por isso chegue cedo! Assim você poderá resolver imprevistos com mais calma e organizar cadeiras, preparar o projet
O GitHub não ta colocando minha sugestão no lugar todo que eu quero... Só pra deixar mais claro, eu estou me referindo a todo o conteúdo:

```
As pessoas responsáveis muito provavelmente vão precisar preparar o lugar para o evento, organizando cadeiras, recebendo os palestrantes ou participantes,
Os responsáveis pela organização do encontro precisarão preparar o local do evento, por isso chegue cedo! Assim você poderá resolver imprevistos com mais calma e organizar cadeiras, preparar o projetor, receber os palestrantes e participantes.
```

2019-10-13 18:07 UTC, naanadr commented on arquivos/ORGANIZACAO-DIA.md
> +
Esse paragrafo ta precisando de uns pontos, ta muito extenso e sem pontos. Estou sugerindo essa organização de frases. 

```suggestion
Muitas vezes os encontros acontecem, por exemplo, em salas de universidades. Como provavelmente, nem todos os participantes conhecerão o local, muitos acabam se perdendo e não encontram com facilidade a sala do evento. Por isso, sinalize bem onde ocorrerá o evento! 
```

2019-10-13 18:08 UTC, naanadr commented on arquivos/ORGANIZACAO-DIA.md
> +
Esse paragrafo ta precisando de uns pontos, ta muito extenso e sem pontos. Estou sugerindo essa organização de frases. 

```suggestion
Muitas vezes os encontros acontecem, por exemplo, em salas de universidades. Como provavelmente, nem todos os participantes conhecerão o local, muitos acabam se perdendo e não encontram com facilidade a sala do evento. Por isso, sinalize bem onde ocorrerá o evento! 
```

2019-10-13 18:09 UTC, naanadr commented on arquivos/ORGANIZACAO-DIA.md
> +
Esse negocio de ficar selecionando várias linhas ta bugado pra mim kkkk 

Mas tu deve ter entendido, é a linha 18.

2019-10-13 18:55 UTC, naanadr approved these changes

2019-10-13 19:01 UTC, naanadr approved these changes

2019-10-13 19:01 UTC, merged