Cria versão em inglês
pugpe/meetup-cookbook pull request #5
Opened 2019-10-11 20:41 UTC by lmmc2

2019-10-12 03:26 UTC, naanadr requested changes

2019-10-12 03:26 UTC, naanadr commented on README-en.md
> + 1. [Main Pipeline](arquivos/english/PIPELINE.md)
```suggestion
 1. [Main Pipeline](files/english/PIPELINE.md)
```

Já que vamos ter várias línguas ou podemos

2019-10-12 03:26 UTC, naanadr commented on README-en.md
> + 4. [Campaign tips](arquivos/english/CAMPAIGN.md)
```suggestion
 4. [Promotion tips](arquivos/english/PROMOTION.md)
```

Acho que faz mais sentido.

2019-10-12 03:26 UTC, naanadr commented on README-en.md
> +>This repository serves as a guide for organizing and planning a [PUG-PE (Python User Group - Pernambuco)](http://pycon.pug.pe) event
```suggestion
>This repository serves as a guide for organizing and planning a [PUG-PE (Python User Group - Pernambuco)](http://pycon.pug.pe) meetup  
```
Faz mais sentido, né? .-.

2019-10-12 03:26 UTC, naanadr commented on README-en.md
> +- Leia esta página em [Português](/README.md)
```suggestion
- Leia esta página em [Português](files/portuguese/README.md)
```

Já que vamos ter várias línguas, seria melhor inserir o português no bolo também.

2019-10-12 03:28 UTC, naanadr commented
> _No description provided._

Adicionar uma descrição no PR, ainda não fizemos um template, porque acabamos de criar o repositório mais seria legal ter um PR descrito e tudo mais.

2019-10-12 10:56 UTC, lmmc2 commented
Oie!
Foi mal por não ter colocado descrição no PR! :x
Sobre as alterações, fiz as primeiras, a última estou com uma dúvida. Queres que o README que vai ficar na raiz sendo mostrado primeiro seja o em inglês?

2019-10-12 15:46 UTC, naanadr commented
> Oie!
> Foi mal por não ter colocado descrição no PR! :x
> Sobre as alterações, fiz as primeiras, a última estou com uma dúvida. Queres que o README que vai ficar na raiz sendo mostrado primeiro seja o em inglês?

Acho que em português seria melhor, porque somos um grupo local. O que tu acha @davidpierre21 ?

2019-10-12 16:38 UTC, davidpierre21 commented
> > Oie!
> > Foi mal por não ter colocado descrição no PR! :x
> > Sobre as alterações, fiz as primeiras, a última estou com uma dúvida. Queres que o README que vai ficar na raiz sendo mostrado primeiro seja o em inglês?
> 
> Oii, continua sem descrição kkkk
> 
> Acho que em português seria melhor, porque somos um grupo local. O que tu acha @davidpierre21 ?

Acho que Português como principal é melhor, mesmo 😄

2019-10-12 19:20 UTC, lmmc2 commented
Massa, concordo, então desconsidero a última sugestão, né? Para não tirar o português da raiz

2019-10-13 17:24 UTC, naanadr commented
> Massa, concordo, então desconsidero a última sugestão, né? Para não tirar o português da raiz

Uhum, foi mal errei ali no Review... o README.md da raiz é o em português mesmo. o resto do conteúdo em português em que fica na pastinha `files/portuguese`

2019-10-13 18:12 UTC, naanadr approved these changes

2019-10-13 18:37 UTC, naanadr approved these changes

2019-10-13 18:37 UTC, merged